@api_HostAddress = http://ec2-3-15-221-241.us-east-2.compute.amazonaws.com:8080

GET {{api_HostAddress}}/users/
Accept: application/json
###

POST {{api_HostAddress}}/users/
Content-Type: application/json

{ "name": "Bob" }
###
